dist: trusty
language: java
sudo: enabled
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
before_install:
  - export TZ=Brazil/East
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: 3214184f-10d8-43e1-ac11-54b371913f56
  app: api-wallet-test
  on:
    repo: alisson-amaral-silva/walletAPI