dist: trusty
language: java
sudo: true
jdk:
  - oraclejdk8
  - addons:
      apt:
        packages:
          - oracle-java8-installer
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: $SECURE_KEY
  app: $APP